apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "classicpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "classicpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "classicpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "classicpress.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ print .Values.classicpress .Values.database | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "classicpress.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: classicpress
          image: {{ include "classicpress.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CLASSICPRESS_DB_HOST
              value: {{ printf "%s:%v" (include "classicpress.database.host" .) .Values.database.port | quote }}
            - name: CLASSICPRESS_DB_NAME
              value: {{ .Values.database.name | quote }}
            - name: CLASSICPRESS_DB_USER
              value: {{ .Values.database.user | quote }}
            - name: CLASSICPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "classicpress.database.secretName" . }}
                  key: {{ include "classicpress.database.passwordKey" . }}
            - name: CLASSICPRESS_DB_CHARSET
              value: {{ .Values.database.charset | quote }}
            - name: CLASSICPRESS_DB_COLLATE
              value: {{ .Values.database.collate | quote }}
            - name: CLASSICPRESS_TABLE_PREFIX
              value: {{ .Values.classicpress.tablePrefix | quote }}
            {{- if .Values.classicpress.debug }}
            - name: CLASSICPRESS_CP_DEBUG
              value: "1"
            {{- end }}
            {{- with .Values.classicpress.configExtra }}
            - name: CLASSICPRESS_CONFIG_EXTRA
              value: {{ . | quote }}
            {{- end }}
            {{- range $key := list "AUTH_KEY" "SECURE_AUTH_KEY" "LOGGED_IN_KEY" "NONCE_KEY" "AUTH_SALT" "SECURE_AUTH_SALT" "LOGGED_IN_SALT" "NONCE_SALT" }}
            - name: CLASSICPRESS_{{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "classicpress.salts.secretName" $ }}
                  key: {{ $key }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/www/html
              {{- with .Values.persistence.subPath }}
              subPath: {{ . }}
              {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "classicpress.pvcName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
