{{- if not .Values.database.existingSecret }}
{{- $name := printf "%s-db" (include "classicpress.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "classicpress.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ include "classicpress.retainedValue" (dict "secret" $existing "key" "password" "default" (default (randAlphaNum 24) .Values.database.password)) }}
{{- end }}
